/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kalkulator;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class AplikasiKalkulator_MuhammadAzril extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKalkulator_MuhammadAzril
     */
    public AplikasiKalkulator_MuhammadAzril() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        JBC = new javax.swing.JButton();
        JBB = new javax.swing.JButton();
        JBbagi = new javax.swing.JButton();
        JBE = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JBX = new javax.swing.JButton();
        JBmin = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JBpls = new javax.swing.JButton();
        JBsadeng = new javax.swing.JButton();
        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        JBpersen = new javax.swing.JButton();
        JB0 = new javax.swing.JButton();
        Jbtitik = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Layar = new javax.swing.JTextField();

        jButton13.setText("jButton1");
        jButton13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        JBC.setBackground(new java.awt.Color(0, 204, 204));
        JBC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBC.setText("C");
        JBC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCActionPerformed(evt);
            }
        });

        JBB.setBackground(new java.awt.Color(0, 204, 204));
        JBB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JBB.setText("<-");
        JBB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBActionPerformed(evt);
            }
        });

        JBbagi.setBackground(new java.awt.Color(0, 204, 204));
        JBbagi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBbagi.setText("/");
        JBbagi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbagiActionPerformed(evt);
            }
        });

        JBE.setBackground(new java.awt.Color(0, 204, 204));
        JBE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBE.setText("E");
        JBE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEActionPerformed(evt);
            }
        });

        JB7.setBackground(new java.awt.Color(0, 204, 204));
        JB7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB7.setText("7");
        JB7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB7ActionPerformed(evt);
            }
        });

        JB5.setBackground(new java.awt.Color(0, 204, 204));
        JB5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB5.setText("5");
        JB5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });

        JB8.setBackground(new java.awt.Color(0, 204, 204));
        JB8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB8.setText("8");
        JB8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB8ActionPerformed(evt);
            }
        });

        JB9.setBackground(new java.awt.Color(0, 204, 204));
        JB9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB9.setText("9");
        JB9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB9ActionPerformed(evt);
            }
        });

        JB6.setBackground(new java.awt.Color(0, 204, 204));
        JB6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB6.setText("6");
        JB6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB6ActionPerformed(evt);
            }
        });

        JBX.setBackground(new java.awt.Color(0, 204, 204));
        JBX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBX.setText("X");
        JBX.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBXActionPerformed(evt);
            }
        });

        JBmin.setBackground(new java.awt.Color(0, 204, 204));
        JBmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JBmin.setText("-");
        JBmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBminActionPerformed(evt);
            }
        });

        JB4.setBackground(new java.awt.Color(0, 204, 204));
        JB4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB4.setText("4");
        JB4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });

        JB3.setBackground(new java.awt.Color(0, 204, 204));
        JB3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB3.setText("3");
        JB3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        JBpls.setBackground(new java.awt.Color(0, 204, 204));
        JBpls.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JBpls.setText("+");
        JBpls.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBpls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBplsActionPerformed(evt);
            }
        });

        JBsadeng.setBackground(new java.awt.Color(153, 153, 153));
        JBsadeng.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBsadeng.setText("=");
        JBsadeng.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBsadeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsadengActionPerformed(evt);
            }
        });

        JB1.setBackground(new java.awt.Color(0, 204, 204));
        JB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB1.setText("1");
        JB1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB2.setBackground(new java.awt.Color(0, 204, 204));
        JB2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB2.setText("2");
        JB2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        JBpersen.setBackground(new java.awt.Color(0, 204, 204));
        JBpersen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBpersen.setText("%");
        JBpersen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpersenActionPerformed(evt);
            }
        });

        JB0.setBackground(new java.awt.Color(0, 204, 204));
        JB0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB0.setText("0");
        JB0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB0ActionPerformed(evt);
            }
        });

        Jbtitik.setBackground(new java.awt.Color(0, 204, 204));
        Jbtitik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jbtitik.setText(".");
        Jbtitik.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Jbtitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtitikActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        Layar.setEditable(false);
        Layar.setBackground(new java.awt.Color(0, 153, 153));
        Layar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Layar.setText("                    0 ");
        Layar.setBorder(null);
        Layar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 175, Short.MAX_VALUE)
                .addComponent(Layar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Layar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JBC, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(JBE, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JBB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JBbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(JB7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JB8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JB9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JBX, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(JB4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JB5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JB6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JBmin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(JB1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JB2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JBpls, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(JBpersen, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JB0, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Jbtitik, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JBsadeng, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBE, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBX, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBpls, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBpersen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbtitik, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBsadeng, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String operand = "";

    double hasil, operandSatu, operandDua, operandTiga;
    private void JB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB7ActionPerformed
        operand += "7";
        Layar.setText(operand);
// TODO add your handling code here:
    }//GEN-LAST:event_JB7ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
        operand += "4";
        Layar.setText(operand);
// TODO add your handling code here:
    }//GEN-LAST:event_JB4ActionPerformed

    private void JBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCActionPerformed
        Layar.setText("");
        operandSatu = 0.0;
        operandDua = 0.0;
        hasil = 0.0;
        operand = "";
         pls ="";
        min ="";
        X ="";
        bgi ="";
         sen ="";
// TODO add your handling code here:
    }//GEN-LAST:event_JBCActionPerformed

    private void JB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB9ActionPerformed
        operand += "9";
        Layar.setText(operand);
        // TODO add your handling code here:
    }//GEN-LAST:event_JB9ActionPerformed

    private void JBminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBminActionPerformed
        operandSatu = Double.parseDouble(operand);
        min = "-";
        operand = "";
        Layar.setText("-");
        // TODO add your handling code here:
    }//GEN-LAST:event_JBminActionPerformed

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        operand += "1";
        Layar.setText(operand);
        // TODO add your handling code here:
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        operand += "2";
        Layar.setText(operand);
// TODO add your handling code here:
    }//GEN-LAST:event_JB2ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
        operand += "3";
        Layar.setText(operand);
// TODO add your handling code here:
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB0ActionPerformed
        operand += "0";
        Layar.setText(operand);
// TODO add your handling code here:
    }//GEN-LAST:event_JB0ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
        operand += "5";
        Layar.setText(operand);
// TODO add your handling code here:
    }//GEN-LAST:event_JB5ActionPerformed

    private void JB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB6ActionPerformed
        operand += "6";
        Layar.setText(operand);
        // TODO add your handling code here:
    }//GEN-LAST:event_JB6ActionPerformed

    private void JB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB8ActionPerformed
        operand += "8";
        Layar.setText(operand);
        // TODO add your handling code here:
    }//GEN-LAST:event_JB8ActionPerformed

   String pls ="";
   String min ="";
   String X ="";
   String bgi ="";
   String sen ="";
    private void JBsadengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsadengActionPerformed
        if (pls.equals("+")) {
            operandDua = Double.parseDouble(operand);
            hasil = operandSatu+operandDua;
            Layar.setText(" "+hasil);
        } else if (min.equals("-")) {
            operandDua = Double.parseDouble(operand);
            hasil = operandSatu-operandDua;
            Layar.setText(" "+hasil);
        } else if (sen.equals("%")) {
            operandDua = Double.parseDouble(operand);
            hasil = operandSatu/operandDua;
            Layar.setText(" "+hasil);
        } else if (bgi.equals("/")) {
            operandDua = Double.parseDouble(operand);
            hasil = operandSatu/operandDua;
            Layar.setText(" "+hasil);
        } else {
            JOptionPane.showMessageDialog(null, "Cek kembali nilainya!!!");
        }
//        operandTiga = Double.parseDouble(String.valueOf(hasil));
//        operandSatu = hasil;
//        Layar.setText("" + hasil);
        // TODO add your handling code here:
    }//GEN-LAST:event_JBsadengActionPerformed

    private void JBEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEActionPerformed
        int exit = JOptionPane.showConfirmDialog(null, "yakin", "Confirm dialog", JOptionPane.YES_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_JBEActionPerformed

    private void JBplsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBplsActionPerformed
     operandSatu = Double.parseDouble(operand);
        pls = "+";
        operand = "";
        Layar.setText("+");
        // TODO add your handling code here:
    }//GEN-LAST:event_JBplsActionPerformed

    private void JBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBXActionPerformed
        operandSatu = Double.parseDouble(operand);
        X = "*";
        operand = "";
        Layar.setText("X");
// TODO add your handling code here:
    }//GEN-LAST:event_JBXActionPerformed

    private void JBbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbagiActionPerformed
        operandSatu = Double.parseDouble(operand);
        bgi = "/";
        operand = "";
        Layar.setText("/");
// TODO add your handling code here:
    }//GEN-LAST:event_JBbagiActionPerformed

    private void JBpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpersenActionPerformed
        operandSatu = Double.parseDouble(operand);
        sen = "%";
       
       if (sen.isEmpty()) {
            operandSatu = Double.parseDouble(operand) / 100;
            operand = String.valueOf(operandSatu);
        } else {
            operandDua = Double.parseDouble(operand) / 100;
            operand = String.valueOf(operandDua);
        }
        Layar.setText(operand);
// TODO add your handling code here:
    }//GEN-LAST:event_JBpersenActionPerformed

    private void JbtitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtitikActionPerformed
        operand += ".";
        Layar.setText(operand);
// TODO add your handling code here:
    }//GEN-LAST:event_JbtitikActionPerformed

    private void LayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LayarActionPerformed

    private void JBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBActionPerformed
    if (Layar.getText().length() <=1){
        Layar.setText("0");
        operand="";
    }else {
        operand = Layar.getText().substring(0,Layar.getText().length()-1);
        Layar.setText(operand);
    }
    
// TODO add your handling code here:
    }//GEN-LAST:event_JBBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator_MuhammadAzril.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator_MuhammadAzril.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator_MuhammadAzril.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator_MuhammadAzril.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKalkulator_MuhammadAzril().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB0;
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private javax.swing.JButton JBB;
    private javax.swing.JButton JBC;
    private javax.swing.JButton JBE;
    private javax.swing.JButton JBX;
    private javax.swing.JButton JBbagi;
    private javax.swing.JButton JBmin;
    private javax.swing.JButton JBpersen;
    private javax.swing.JButton JBpls;
    private javax.swing.JButton JBsadeng;
    private javax.swing.JButton Jbtitik;
    private javax.swing.JTextField Layar;
    private javax.swing.JButton jButton13;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
