/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Userinterface;

/**
 *
 * @author acer
 */
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;

public class AplikasiPenghitungJumlahHari extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenghitungJumlahHari
     */
    public AplikasiPenghitungJumlahHari() {

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CMBbln = new javax.swing.JComboBox<>();
        TFth = new javax.swing.JTextField();
        BTHitung = new javax.swing.JButton();
        BTHapus = new javax.swing.JButton();
        BTKeluar = new javax.swing.JButton();
        BTsimpan = new javax.swing.JButton();
        JHL = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tahun");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Bulan");

        CMBbln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Febuari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        CMBbln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBblnActionPerformed(evt);
            }
        });

        TFth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFthActionPerformed(evt);
            }
        });
        TFth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFthKeyTyped(evt);
            }
        });

        BTHitung.setText("Hitung");
        BTHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTHitungActionPerformed(evt);
            }
        });

        BTHapus.setText("Hapus");
        BTHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTHapusActionPerformed(evt);
            }
        });

        BTKeluar.setText("Keluar");
        BTKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTKeluarActionPerformed(evt);
            }
        });

        BTsimpan.setText("Simpan");
        BTsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsimpanActionPerformed(evt);
            }
        });

        JHL.setEditable(false);
        JHL.setBackground(new java.awt.Color(255, 102, 255));
        JHL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JHL.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(BTHitung)
                        .addGap(18, 18, 18)
                        .addComponent(BTsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(BTHapus)
                        .addGap(18, 18, 18)
                        .addComponent(BTKeluar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFth)
                            .addComponent(CMBbln, 0, 128, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(JHL)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBbln, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TFth, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(JHL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMBblnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBblnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMBblnActionPerformed

    private void BTsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsimpanActionPerformed
        // TODO add your handling code here:
        try {
            BufferedWriter out = new BufferedWriter(new FileWriter("JumlahHari.txt"));
            out.write(JHL.getText());
            JOptionPane.showMessageDialog(null, "Berhasil Disimpan Dalam File");
            out.close();
        } catch (Exception E) {
            System.err.println("Eror : " + E.getMessage());
        }
    }//GEN-LAST:event_BTsimpanActionPerformed

    private void BTKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTKeluarActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "yakin", "Confirm dialog", JOptionPane.YES_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BTKeluarActionPerformed

    private void BTHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTHapusActionPerformed
        // TODO add your handling code here:
        JHL.setText("");
        TFth.setText("");
        CMBbln.setSelectedItem("Januari");
    }//GEN-LAST:event_BTHapusActionPerformed
    private void numberFilter(java.awt.event.KeyEvent evt) {
        char input = evt.getKeyChar();
        if (!Character.isDigit(input)) {
            new AplikasiPenghitungJumlahHari().getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Hanya number");
            evt.consume();
        }
    }

    private void BTHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTHitungActionPerformed
        // TODO add your handling code here:
        if (TFth.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Eror: Isilah Tahun Kosong!");
        } else {
            int tahun = Integer.parseInt(TFth.getText());
            int Jumlahhari;
            if (CMBbln.getSelectedItem().equals("Febuari")) {
                if (((tahun % 4 == 0) && !(tahun % 100 == 0)) || (tahun % 400 == 0)) {
                    Jumlahhari = 29;
                } else {
                    Jumlahhari = 28;
                }
            } else if (CMBbln.getSelectedItem().equals("April")
                    || CMBbln.getSelectedItem().equals("Juni")
                    || CMBbln.getSelectedItem().equals("September")
                    || CMBbln.getSelectedItem().equals("November")) {
                Jumlahhari = 30;
            } else {
                Jumlahhari = 31;
            }
            JHL.setText("Jumlah Hari pada bulan " + CMBbln.getSelectedItem() + " Tahun " + tahun + " Adalah " + Jumlahhari);
        }
    }//GEN-LAST:event_BTHitungActionPerformed

    private void TFthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFthKeyTyped
        // TODO add your handling code here:
        numberFilter(evt);
    }//GEN-LAST:event_TFthKeyTyped

    private void TFthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFthActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TFthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginfrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTHapus;
    private javax.swing.JButton BTHitung;
    private javax.swing.JButton BTKeluar;
    private javax.swing.JButton BTsimpan;
    private javax.swing.JComboBox<String> CMBbln;
    private javax.swing.JTextField JHL;
    private javax.swing.JTextField TFth;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
